# Generated by Django 3.2.13 on 2022-05-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_newsletter_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Suscrito', 'verbose_name_plural': 'Suscritos'},
        ),
    ]
