# Generated by Django 3.2.13 on 2022-05-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteo',
            name='email',
            field=models.CharField(max_length=80, unique=True, verbose_name='Email'),
        ),
    ]
