# Generated by Django 3.2.13 on 2022-05-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0002_alter_sorteo_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sorteo',
            options={'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
        migrations.RenameField(
            model_name='sorteo',
            old_name='genero',
            new_name='genere',
        ),
    ]
